# Generated by Django 3.0.3 on 2020-08-24 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ptop', '0024_auto_20200818_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='troublegroup',
            name='causetype',
            field=models.CharField(blank=True, choices=[('CT_ACC', '偶発故障'), ('CT_DET', '経年劣化'), ('CT_OPE', 'オペミス'), ('CT_INI', '初期不良'), ('CT_DES', '設計不良'), ('CT_MAN', '製作不良')], max_length=20, null=True, verbose_name='原因の類型'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='classify_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troublegroup_classified', to=settings.AUTH_USER_MODEL, verbose_name='分類者'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='common_action',
            field=models.TextField(blank=True, null=True, verbose_name='主要な対処法'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='errors',
            field=models.ManyToManyField(blank=True, null=True, to='ptop.Error', verbose_name='エラーメッセージ'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='first_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='初発日時'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='handling_status',
            field=models.CharField(blank=True, choices=[('HS_IGN', '放置可能'), ('HS_YET', '未対策'), ('HS_SEE', '様子見'), ('HS_WAT', '重点監視'), ('HS_AVO', '運用回避'), ('HS_VEN', 'メーカー依頼中'), ('HS_FIN', '解決済')], max_length=20, null=True, verbose_name='対処状況'),
        ),
        migrations.AddField(
            model_name='troublegroup',
            name='vender_status',
            field=models.CharField(blank=True, choices=[('VS_NON', '連絡不要'), ('VS_YET', '未連絡'), ('VS_RWA', '連絡済み回答待ち'), ('VS_RPL', '連絡済み対処予定'), ('VS_RPL', '連絡済み様子見'), ('VS_FIN', '対処完了')], max_length=20, null=True, verbose_name='メーカー連絡状況'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='errors',
            field=models.ManyToManyField(blank=True, null=True, to='ptop.Error', verbose_name='エラーメッセージ'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='handling_operators',
            field=models.ManyToManyField(limit_choices_to=models.Q(('groups__name', 'Operator'), ('is_active', True)), to=settings.AUTH_USER_MODEL, verbose_name='対応者'),
        ),
        migrations.AlterField(
            model_name='troubleevent',
            name='input_operator',
            field=models.ForeignKey(limit_choices_to=models.Q(('groups__name', 'Operator'), ('is_active', True)), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='troubleevent_inputed', to=settings.AUTH_USER_MODEL, verbose_name='入力者'),
        ),
    ]
